/*
 * This file is generated by jOOQ.
 */
package com.kopivad.testingsystem.domain.db;


import com.kopivad.testingsystem.domain.db.tables.Answers;
import com.kopivad.testingsystem.domain.db.tables.Questions;
import com.kopivad.testingsystem.domain.db.tables.QuizResults;
import com.kopivad.testingsystem.domain.db.tables.QuizSessions;
import com.kopivad.testingsystem.domain.db.tables.Quizzes;
import com.kopivad.testingsystem.domain.db.tables.UserResponces;
import com.kopivad.testingsystem.domain.db.tables.UserRoles;
import com.kopivad.testingsystem.domain.db.tables.Users;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -947785803;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.answers</code>.
     */
    public final Answers ANSWERS = com.kopivad.testingsystem.domain.db.tables.Answers.ANSWERS;

    /**
     * The table <code>public.questions</code>.
     */
    public final Questions QUESTIONS = com.kopivad.testingsystem.domain.db.tables.Questions.QUESTIONS;

    /**
     * The table <code>public.quiz_results</code>.
     */
    public final QuizResults QUIZ_RESULTS = com.kopivad.testingsystem.domain.db.tables.QuizResults.QUIZ_RESULTS;

    /**
     * The table <code>public.quiz_sessions</code>.
     */
    public final QuizSessions QUIZ_SESSIONS = com.kopivad.testingsystem.domain.db.tables.QuizSessions.QUIZ_SESSIONS;

    /**
     * The table <code>public.quizzes</code>.
     */
    public final Quizzes QUIZZES = com.kopivad.testingsystem.domain.db.tables.Quizzes.QUIZZES;

    /**
     * The table <code>public.user_responces</code>.
     */
    public final UserResponces USER_RESPONCES = com.kopivad.testingsystem.domain.db.tables.UserResponces.USER_RESPONCES;

    /**
     * The table <code>public.user_roles</code>.
     */
    public final UserRoles USER_ROLES = com.kopivad.testingsystem.domain.db.tables.UserRoles.USER_ROLES;

    /**
     * The table <code>public.users</code>.
     */
    public final Users USERS = com.kopivad.testingsystem.domain.db.tables.Users.USERS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.ANSWERS_ID_SEQ,
            Sequences.QUESTIONS_ID_SEQ,
            Sequences.QUIZ_RESULTS_ID_SEQ,
            Sequences.QUIZ_SESSIONS_ID_SEQ,
            Sequences.QUIZZES_ID_SEQ,
            Sequences.USER_RESPONCES_ID_SEQ,
            Sequences.USERS_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Answers.ANSWERS,
            Questions.QUESTIONS,
            QuizResults.QUIZ_RESULTS,
            QuizSessions.QUIZ_SESSIONS,
            Quizzes.QUIZZES,
            UserResponces.USER_RESPONCES,
            UserRoles.USER_ROLES,
            Users.USERS);
    }
}
