/*
 * This file is generated by jOOQ.
 */
package com.kopivad.testingsystem.domain.db;


import javax.annotation.processing.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.answers_id_seq</code>
     */
    public static final Sequence<Long> ANSWERS_ID_SEQ = new SequenceImpl<Long>("answers_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.questions_id_seq</code>
     */
    public static final Sequence<Long> QUESTIONS_ID_SEQ = new SequenceImpl<Long>("questions_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.quiz_results_id_seq</code>
     */
    public static final Sequence<Long> QUIZ_RESULTS_ID_SEQ = new SequenceImpl<Long>("quiz_results_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.quiz_sessions_id_seq</code>
     */
    public static final Sequence<Long> QUIZ_SESSIONS_ID_SEQ = new SequenceImpl<Long>("quiz_sessions_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.quizzes_id_seq</code>
     */
    public static final Sequence<Long> QUIZZES_ID_SEQ = new SequenceImpl<Long>("quizzes_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.user_responces_id_seq</code>
     */
    public static final Sequence<Long> USER_RESPONCES_ID_SEQ = new SequenceImpl<Long>("user_responces_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.users_id_seq</code>
     */
    public static final Sequence<Long> USERS_ID_SEQ = new SequenceImpl<Long>("users_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
