/*
 * This file is generated by jOOQ.
 */
package com.kopivad.testingsystem.domain.db;


import com.kopivad.testingsystem.domain.db.tables.Answers;
import com.kopivad.testingsystem.domain.db.tables.Questions;
import com.kopivad.testingsystem.domain.db.tables.QuizResults;
import com.kopivad.testingsystem.domain.db.tables.QuizSessions;
import com.kopivad.testingsystem.domain.db.tables.Quizzes;
import com.kopivad.testingsystem.domain.db.tables.UserResponces;
import com.kopivad.testingsystem.domain.db.tables.UserRoles;
import com.kopivad.testingsystem.domain.db.tables.Users;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.answers</code>.
     */
    public static final Answers ANSWERS = Answers.ANSWERS;

    /**
     * The table <code>public.questions</code>.
     */
    public static final Questions QUESTIONS = Questions.QUESTIONS;

    /**
     * The table <code>public.quiz_results</code>.
     */
    public static final QuizResults QUIZ_RESULTS = QuizResults.QUIZ_RESULTS;

    /**
     * The table <code>public.quiz_sessions</code>.
     */
    public static final QuizSessions QUIZ_SESSIONS = QuizSessions.QUIZ_SESSIONS;

    /**
     * The table <code>public.quizzes</code>.
     */
    public static final Quizzes QUIZZES = Quizzes.QUIZZES;

    /**
     * The table <code>public.user_responces</code>.
     */
    public static final UserResponces USER_RESPONCES = UserResponces.USER_RESPONCES;

    /**
     * The table <code>public.user_roles</code>.
     */
    public static final UserRoles USER_ROLES = UserRoles.USER_ROLES;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
