/*
 * This file is generated by jOOQ.
 */
package com.kopivad.testingsystem.domain.db.tables.records;


import com.kopivad.testingsystem.domain.db.tables.UserResponces;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserResponcesRecord extends UpdatableRecordImpl<UserResponcesRecord> implements Record4<Long, Long, Long, Long> {

    private static final long serialVersionUID = -90725592;

    /**
     * Setter for <code>public.user_responces.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.user_responces.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.user_responces.answer_id</code>.
     */
    public void setAnswerId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.user_responces.answer_id</code>.
     */
    public Long getAnswerId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.user_responces.question_id</code>.
     */
    public void setQuestionId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.user_responces.question_id</code>.
     */
    public Long getQuestionId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.user_responces.session_id</code>.
     */
    public void setSessionId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.user_responces.session_id</code>.
     */
    public Long getSessionId() {
        return (Long) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, Long, Long, Long> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, Long, Long, Long> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return UserResponces.USER_RESPONCES.ID;
    }

    @Override
    public Field<Long> field2() {
        return UserResponces.USER_RESPONCES.ANSWER_ID;
    }

    @Override
    public Field<Long> field3() {
        return UserResponces.USER_RESPONCES.QUESTION_ID;
    }

    @Override
    public Field<Long> field4() {
        return UserResponces.USER_RESPONCES.SESSION_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getAnswerId();
    }

    @Override
    public Long component3() {
        return getQuestionId();
    }

    @Override
    public Long component4() {
        return getSessionId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getAnswerId();
    }

    @Override
    public Long value3() {
        return getQuestionId();
    }

    @Override
    public Long value4() {
        return getSessionId();
    }

    @Override
    public UserResponcesRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public UserResponcesRecord value2(Long value) {
        setAnswerId(value);
        return this;
    }

    @Override
    public UserResponcesRecord value3(Long value) {
        setQuestionId(value);
        return this;
    }

    @Override
    public UserResponcesRecord value4(Long value) {
        setSessionId(value);
        return this;
    }

    @Override
    public UserResponcesRecord values(Long value1, Long value2, Long value3, Long value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserResponcesRecord
     */
    public UserResponcesRecord() {
        super(UserResponces.USER_RESPONCES);
    }

    /**
     * Create a detached, initialised UserResponcesRecord
     */
    public UserResponcesRecord(Long id, Long answerId, Long questionId, Long sessionId) {
        super(UserResponces.USER_RESPONCES);

        set(0, id);
        set(1, answerId);
        set(2, questionId);
        set(3, sessionId);
    }
}
