/*
 * This file is generated by jOOQ.
 */
package com.kopivad.quizzes.domain.db;


import com.kopivad.quizzes.domain.db.tables.*;
import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import javax.annotation.processing.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 143536560;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.answers</code>.
     */
    public final Answers ANSWERS = com.kopivad.quizzes.domain.db.tables.Answers.ANSWERS;

    /**
     * The table <code>public.groups</code>.
     */
    public final Groups GROUPS = com.kopivad.quizzes.domain.db.tables.Groups.GROUPS;

    /**
     * The table <code>public.groups_quizzes</code>.
     */
    public final GroupsQuizzes GROUPS_QUIZZES = com.kopivad.quizzes.domain.db.tables.GroupsQuizzes.GROUPS_QUIZZES;

    /**
     * The table <code>public.groups_users</code>.
     */
    public final GroupsUsers GROUPS_USERS = com.kopivad.quizzes.domain.db.tables.GroupsUsers.GROUPS_USERS;

    /**
     * The table <code>public.questions</code>.
     */
    public final Questions QUESTIONS = com.kopivad.quizzes.domain.db.tables.Questions.QUESTIONS;

    /**
     * The table <code>public.quiz_answers</code>.
     */
    public final QuizAnswers QUIZ_ANSWERS = com.kopivad.quizzes.domain.db.tables.QuizAnswers.QUIZ_ANSWERS;

    /**
     * The table <code>public.quiz_histories</code>.
     */
    public final QuizHistories QUIZ_HISTORIES = com.kopivad.quizzes.domain.db.tables.QuizHistories.QUIZ_HISTORIES;

    /**
     * The table <code>public.quiz_sessions</code>.
     */
    public final QuizSessions QUIZ_SESSIONS = com.kopivad.quizzes.domain.db.tables.QuizSessions.QUIZ_SESSIONS;

    /**
     * The table <code>public.quizzes</code>.
     */
    public final Quizzes QUIZZES = com.kopivad.quizzes.domain.db.tables.Quizzes.QUIZZES;

    /**
     * The table <code>public.steps</code>.
     */
    public final Steps STEPS = com.kopivad.quizzes.domain.db.tables.Steps.STEPS;

    /**
     * The table <code>public.users</code>.
     */
    public final Users USERS = com.kopivad.quizzes.domain.db.tables.Users.USERS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.ANSWERS_ID_SEQ,
            Sequences.GROUPS_ID_SEQ,
            Sequences.QUESTIONS_ID_SEQ,
            Sequences.QUIZ_ANSWERS_ID_SEQ,
            Sequences.QUIZ_HISTORY_ID_SEQ,
            Sequences.QUIZ_SESSIONS_ID_SEQ,
            Sequences.STEPS_ID_SEQ,
            Sequences.TABLE_NAME_ID_SEQ,
            Sequences.USERS_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Answers.ANSWERS,
            Groups.GROUPS,
            GroupsQuizzes.GROUPS_QUIZZES,
            GroupsUsers.GROUPS_USERS,
            Questions.QUESTIONS,
            QuizAnswers.QUIZ_ANSWERS,
            QuizHistories.QUIZ_HISTORIES,
            QuizSessions.QUIZ_SESSIONS,
            Quizzes.QUIZZES,
            Steps.STEPS,
            Users.USERS);
    }
}
