/*
 * This file is generated by jOOQ.
 */
package com.kopivad.quizzes.domain.db;


import com.kopivad.quizzes.domain.db.tables.Answers;
import com.kopivad.quizzes.domain.db.tables.ApiClients;
import com.kopivad.quizzes.domain.db.tables.Questions;
import com.kopivad.quizzes.domain.db.tables.Quizzes;
import com.kopivad.quizzes.domain.db.tables.Usr;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -1552582478;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.answers</code>.
     */
    public final Answers ANSWERS = com.kopivad.quizzes.domain.db.tables.Answers.ANSWERS;

    /**
     * The table <code>public.api_clients</code>.
     */
    public final ApiClients API_CLIENTS = com.kopivad.quizzes.domain.db.tables.ApiClients.API_CLIENTS;

    /**
     * The table <code>public.questions</code>.
     */
    public final Questions QUESTIONS = com.kopivad.quizzes.domain.db.tables.Questions.QUESTIONS;

    /**
     * The table <code>public.quizzes</code>.
     */
    public final Quizzes QUIZZES = com.kopivad.quizzes.domain.db.tables.Quizzes.QUIZZES;

    /**
     * The table <code>public.usr</code>.
     */
    public final Usr USR = com.kopivad.quizzes.domain.db.tables.Usr.USR;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.ANSWERS_ID_SEQ,
            Sequences.API_CLIENTS_ID_SEQ,
            Sequences.QUESTIONS_ID_SEQ,
            Sequences.QUIZZES_ID_SEQ,
            Sequences.USR_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Answers.ANSWERS,
            ApiClients.API_CLIENTS,
            Questions.QUESTIONS,
            Quizzes.QUIZZES,
            Usr.USR);
    }
}
