/*
 * This file is generated by jOOQ.
 */
package com.kopivad.quizzes.domain.db;


import com.kopivad.quizzes.domain.db.tables.Answers;
import com.kopivad.quizzes.domain.db.tables.ApiClients;
import com.kopivad.quizzes.domain.db.tables.EvaluationSteps;
import com.kopivad.quizzes.domain.db.tables.Questions;
import com.kopivad.quizzes.domain.db.tables.QuizAnswers;
import com.kopivad.quizzes.domain.db.tables.QuizHistories;
import com.kopivad.quizzes.domain.db.tables.QuizSessions;
import com.kopivad.quizzes.domain.db.tables.Quizzes;
import com.kopivad.quizzes.domain.db.tables.Usr;
import com.kopivad.quizzes.domain.db.tables.UsrRoles;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.answers</code>.
     */
    public static final Answers ANSWERS = Answers.ANSWERS;

    /**
     * The table <code>public.api_clients</code>.
     */
    public static final ApiClients API_CLIENTS = ApiClients.API_CLIENTS;

    /**
     * The table <code>public.evaluation_steps</code>.
     */
    public static final EvaluationSteps EVALUATION_STEPS = EvaluationSteps.EVALUATION_STEPS;

    /**
     * The table <code>public.questions</code>.
     */
    public static final Questions QUESTIONS = Questions.QUESTIONS;

    /**
     * The table <code>public.quiz_answers</code>.
     */
    public static final QuizAnswers QUIZ_ANSWERS = QuizAnswers.QUIZ_ANSWERS;

    /**
     * The table <code>public.quiz_histories</code>.
     */
    public static final QuizHistories QUIZ_HISTORIES = QuizHistories.QUIZ_HISTORIES;

    /**
     * The table <code>public.quiz_sessions</code>.
     */
    public static final QuizSessions QUIZ_SESSIONS = QuizSessions.QUIZ_SESSIONS;

    /**
     * The table <code>public.quizzes</code>.
     */
    public static final Quizzes QUIZZES = Quizzes.QUIZZES;

    /**
     * The table <code>public.usr</code>.
     */
    public static final Usr USR = Usr.USR;

    /**
     * The table <code>public.usr_roles</code>.
     */
    public static final UsrRoles USR_ROLES = UsrRoles.USR_ROLES;
}
