/*
 * This file is generated by jOOQ.
 */
package com.kopivad.quizzes.domain.db;


import com.kopivad.quizzes.domain.db.tables.*;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.answers</code>.
     */
    public static final Answers ANSWERS = Answers.ANSWERS;

    /**
     * The table <code>public.groups</code>.
     */
    public static final Groups GROUPS = Groups.GROUPS;

    /**
     * The table <code>public.groups_quizzes</code>.
     */
    public static final GroupsQuizzes GROUPS_QUIZZES = GroupsQuizzes.GROUPS_QUIZZES;

    /**
     * The table <code>public.groups_users</code>.
     */
    public static final GroupsUsers GROUPS_USERS = GroupsUsers.GROUPS_USERS;

    /**
     * The table <code>public.questions</code>.
     */
    public static final Questions QUESTIONS = Questions.QUESTIONS;

    /**
     * The table <code>public.quiz_answers</code>.
     */
    public static final QuizAnswers QUIZ_ANSWERS = QuizAnswers.QUIZ_ANSWERS;

    /**
     * The table <code>public.quiz_histories</code>.
     */
    public static final QuizHistories QUIZ_HISTORIES = QuizHistories.QUIZ_HISTORIES;

    /**
     * The table <code>public.quiz_sessions</code>.
     */
    public static final QuizSessions QUIZ_SESSIONS = QuizSessions.QUIZ_SESSIONS;

    /**
     * The table <code>public.quizzes</code>.
     */
    public static final Quizzes QUIZZES = Quizzes.QUIZZES;

    /**
     * The table <code>public.steps</code>.
     */
    public static final Steps STEPS = Steps.STEPS;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
