/*
 * This file is generated by jOOQ.
 */
package com.kopivad.quizzes.domain.db.tables;


import com.kopivad.quizzes.domain.db.Indexes;
import com.kopivad.quizzes.domain.db.Keys;
import com.kopivad.quizzes.domain.db.Public;
import com.kopivad.quizzes.domain.db.tables.records.AnswersRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import javax.annotation.processing.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Answers extends TableImpl<AnswersRecord> {

    private static final long serialVersionUID = -953367270;

    /**
     * The reference instance of <code>public.answers</code>
     */
    public static final Answers ANSWERS = new Answers();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AnswersRecord> getRecordType() {
        return AnswersRecord.class;
    }

    /**
     * The column <code>public.answers.id</code>.
     */
    public final TableField<AnswersRecord, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field("nextval('answers_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.answers.body</code>.
     */
    public final TableField<AnswersRecord, String> BODY = createField(DSL.name("body"), org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.answers.right</code>.
     */
    public final TableField<AnswersRecord, Boolean> RIGHT = createField(DSL.name("right"), org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.answers.question_id</code>.
     */
    public final TableField<AnswersRecord, Long> QUESTION_ID = createField(DSL.name("question_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>public.answers</code> table reference
     */
    public Answers() {
        this(DSL.name("answers"), null);
    }

    /**
     * Create an aliased <code>public.answers</code> table reference
     */
    public Answers(String alias) {
        this(DSL.name(alias), ANSWERS);
    }

    /**
     * Create an aliased <code>public.answers</code> table reference
     */
    public Answers(Name alias) {
        this(alias, ANSWERS);
    }

    private Answers(Name alias, Table<AnswersRecord> aliased) {
        this(alias, aliased, null);
    }

    private Answers(Name alias, Table<AnswersRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Answers(Table<O> child, ForeignKey<O, AnswersRecord> key) {
        super(child, key, ANSWERS);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ANSWERS_PK);
    }

    @Override
    public Identity<AnswersRecord, Long> getIdentity() {
        return Keys.IDENTITY_ANSWERS;
    }

    @Override
    public UniqueKey<AnswersRecord> getPrimaryKey() {
        return Keys.ANSWERS_PK;
    }

    @Override
    public List<UniqueKey<AnswersRecord>> getKeys() {
        return Arrays.<UniqueKey<AnswersRecord>>asList(Keys.ANSWERS_PK);
    }

    @Override
    public List<ForeignKey<AnswersRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<AnswersRecord, ?>>asList(Keys.ANSWERS__ANSWERS_QUESTIONS_ID_FK);
    }

    public Questions questions() {
        return new Questions(this, Keys.ANSWERS__ANSWERS_QUESTIONS_ID_FK);
    }

    @Override
    public Answers as(String alias) {
        return new Answers(DSL.name(alias), this);
    }

    @Override
    public Answers as(Name alias) {
        return new Answers(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Answers rename(String name) {
        return new Answers(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Answers rename(Name name) {
        return new Answers(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, String, Boolean, Long> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
