/*
 * This file is generated by jOOQ.
 */
package com.kopivad.quizzes.domain.db.tables.records;


import com.kopivad.quizzes.domain.db.tables.Answers;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AnswersRecord extends UpdatableRecordImpl<AnswersRecord> implements Record4<Long, String, Boolean, Long> {

    private static final long serialVersionUID = -349408681;

    /**
     * Setter for <code>public.answers.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.answers.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.answers.body</code>.
     */
    public void setBody(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.answers.body</code>.
     */
    public String getBody() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.answers.right</code>.
     */
    public void setRight(Boolean value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.answers.right</code>.
     */
    public Boolean getRight() {
        return (Boolean) get(2);
    }

    /**
     * Setter for <code>public.answers.question_id</code>.
     */
    public void setQuestionId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.answers.question_id</code>.
     */
    public Long getQuestionId() {
        return (Long) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, String, Boolean, Long> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, String, Boolean, Long> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Answers.ANSWERS.ID;
    }

    @Override
    public Field<String> field2() {
        return Answers.ANSWERS.BODY;
    }

    @Override
    public Field<Boolean> field3() {
        return Answers.ANSWERS.RIGHT;
    }

    @Override
    public Field<Long> field4() {
        return Answers.ANSWERS.QUESTION_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getBody();
    }

    @Override
    public Boolean component3() {
        return getRight();
    }

    @Override
    public Long component4() {
        return getQuestionId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getBody();
    }

    @Override
    public Boolean value3() {
        return getRight();
    }

    @Override
    public Long value4() {
        return getQuestionId();
    }

    @Override
    public AnswersRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public AnswersRecord value2(String value) {
        setBody(value);
        return this;
    }

    @Override
    public AnswersRecord value3(Boolean value) {
        setRight(value);
        return this;
    }

    @Override
    public AnswersRecord value4(Long value) {
        setQuestionId(value);
        return this;
    }

    @Override
    public AnswersRecord values(Long value1, String value2, Boolean value3, Long value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AnswersRecord
     */
    public AnswersRecord() {
        super(Answers.ANSWERS);
    }

    /**
     * Create a detached, initialised AnswersRecord
     */
    public AnswersRecord(Long id, String body, Boolean right, Long questionId) {
        super(Answers.ANSWERS);

        set(0, id);
        set(1, body);
        set(2, right);
        set(3, questionId);
    }
}
