/*
 * This file is generated by jOOQ.
 */
package com.kopivad.quizzes.domain.db.tables.records;


import com.kopivad.quizzes.domain.db.tables.EvaluationSteps;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EvaluationStepsRecord extends UpdatableRecordImpl<EvaluationStepsRecord> implements Record5<Long, Integer, String, Long, Integer> {

    private static final long serialVersionUID = 1505754082;

    /**
     * Setter for <code>public.evaluation_steps.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.evaluation_steps.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.evaluation_steps.minTotal</code>.
     */
    public void setMintotal(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.evaluation_steps.minTotal</code>.
     */
    public Integer getMintotal() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.evaluation_steps.rating</code>.
     */
    public void setRating(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.evaluation_steps.rating</code>.
     */
    public String getRating() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.evaluation_steps.quiz_id</code>.
     */
    public void setQuizId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.evaluation_steps.quiz_id</code>.
     */
    public Long getQuizId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.evaluation_steps.maxTotal</code>.
     */
    public void setMaxtotal(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.evaluation_steps.maxTotal</code>.
     */
    public Integer getMaxtotal() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, Integer, String, Long, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, Integer, String, Long, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return EvaluationSteps.EVALUATION_STEPS.ID;
    }

    @Override
    public Field<Integer> field2() {
        return EvaluationSteps.EVALUATION_STEPS.MINTOTAL;
    }

    @Override
    public Field<String> field3() {
        return EvaluationSteps.EVALUATION_STEPS.RATING;
    }

    @Override
    public Field<Long> field4() {
        return EvaluationSteps.EVALUATION_STEPS.QUIZ_ID;
    }

    @Override
    public Field<Integer> field5() {
        return EvaluationSteps.EVALUATION_STEPS.MAXTOTAL;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getMintotal();
    }

    @Override
    public String component3() {
        return getRating();
    }

    @Override
    public Long component4() {
        return getQuizId();
    }

    @Override
    public Integer component5() {
        return getMaxtotal();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getMintotal();
    }

    @Override
    public String value3() {
        return getRating();
    }

    @Override
    public Long value4() {
        return getQuizId();
    }

    @Override
    public Integer value5() {
        return getMaxtotal();
    }

    @Override
    public EvaluationStepsRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public EvaluationStepsRecord value2(Integer value) {
        setMintotal(value);
        return this;
    }

    @Override
    public EvaluationStepsRecord value3(String value) {
        setRating(value);
        return this;
    }

    @Override
    public EvaluationStepsRecord value4(Long value) {
        setQuizId(value);
        return this;
    }

    @Override
    public EvaluationStepsRecord value5(Integer value) {
        setMaxtotal(value);
        return this;
    }

    @Override
    public EvaluationStepsRecord values(Long value1, Integer value2, String value3, Long value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EvaluationStepsRecord
     */
    public EvaluationStepsRecord() {
        super(EvaluationSteps.EVALUATION_STEPS);
    }

    /**
     * Create a detached, initialised EvaluationStepsRecord
     */
    public EvaluationStepsRecord(Long id, Integer mintotal, String rating, Long quizId, Integer maxtotal) {
        super(EvaluationSteps.EVALUATION_STEPS);

        set(0, id);
        set(1, mintotal);
        set(2, rating);
        set(3, quizId);
        set(4, maxtotal);
    }
}
