/*
 * This file is generated by jOOQ.
 */
package com.kopivad.quizzes.domain.db.tables.records;


import com.kopivad.quizzes.domain.db.tables.GroupsUsers;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GroupsUsersRecord extends TableRecordImpl<GroupsUsersRecord> implements Record2<Long, Long> {

    private static final long serialVersionUID = 199691920;

    /**
     * Setter for <code>public.groups_users.group_id</code>.
     */
    public void setGroupId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.groups_users.group_id</code>.
     */
    public Long getGroupId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.groups_users.user_id</code>.
     */
    public void setUserId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.groups_users.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Long, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return GroupsUsers.GROUPS_USERS.GROUP_ID;
    }

    @Override
    public Field<Long> field2() {
        return GroupsUsers.GROUPS_USERS.USER_ID;
    }

    @Override
    public Long component1() {
        return getGroupId();
    }

    @Override
    public Long component2() {
        return getUserId();
    }

    @Override
    public Long value1() {
        return getGroupId();
    }

    @Override
    public Long value2() {
        return getUserId();
    }

    @Override
    public GroupsUsersRecord value1(Long value) {
        setGroupId(value);
        return this;
    }

    @Override
    public GroupsUsersRecord value2(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public GroupsUsersRecord values(Long value1, Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GroupsUsersRecord
     */
    public GroupsUsersRecord() {
        super(GroupsUsers.GROUPS_USERS);
    }

    /**
     * Create a detached, initialised GroupsUsersRecord
     */
    public GroupsUsersRecord(Long groupId, Long userId) {
        super(GroupsUsers.GROUPS_USERS);

        set(0, groupId);
        set(1, userId);
    }
}
