/*
 * This file is generated by jOOQ.
 */
package com.kopivad.quizzes.domain.db.tables.records;


import com.kopivad.quizzes.domain.db.tables.QuizzesGroups;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QuizzesGroupsRecord extends TableRecordImpl<QuizzesGroupsRecord> implements Record2<Long, Long> {

    private static final long serialVersionUID = -1362367626;

    /**
     * Setter for <code>public.quizzes_groups.quiz_id</code>.
     */
    public void setQuizId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.quizzes_groups.quiz_id</code>.
     */
    public Long getQuizId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.quizzes_groups.group_id</code>.
     */
    public void setGroupId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.quizzes_groups.group_id</code>.
     */
    public Long getGroupId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Long, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return QuizzesGroups.QUIZZES_GROUPS.QUIZ_ID;
    }

    @Override
    public Field<Long> field2() {
        return QuizzesGroups.QUIZZES_GROUPS.GROUP_ID;
    }

    @Override
    public Long component1() {
        return getQuizId();
    }

    @Override
    public Long component2() {
        return getGroupId();
    }

    @Override
    public Long value1() {
        return getQuizId();
    }

    @Override
    public Long value2() {
        return getGroupId();
    }

    @Override
    public QuizzesGroupsRecord value1(Long value) {
        setQuizId(value);
        return this;
    }

    @Override
    public QuizzesGroupsRecord value2(Long value) {
        setGroupId(value);
        return this;
    }

    @Override
    public QuizzesGroupsRecord values(Long value1, Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached QuizzesGroupsRecord
     */
    public QuizzesGroupsRecord() {
        super(QuizzesGroups.QUIZZES_GROUPS);
    }

    /**
     * Create a detached, initialised QuizzesGroupsRecord
     */
    public QuizzesGroupsRecord(Long quizId, Long groupId) {
        super(QuizzesGroups.QUIZZES_GROUPS);

        set(0, quizId);
        set(1, groupId);
    }
}
