/*
 * This file is generated by jOOQ.
 */
package com.kopivad.quizzes.domain.db.tables.records;


import com.kopivad.quizzes.domain.db.tables.Quizzes;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.processing.Generated;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QuizzesRecord extends UpdatableRecordImpl<QuizzesRecord> implements Record7<Long, String, String, Integer, Boolean, Timestamp, Long> {

    private static final long serialVersionUID = -1553825322;

    /**
     * Setter for <code>public.quizzes.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.quizzes.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.quizzes.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.quizzes.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.quizzes.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.quizzes.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.quizzes.total</code>.
     */
    public void setTotal(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.quizzes.total</code>.
     */
    public Integer getTotal() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.quizzes.active</code>.
     */
    public void setActive(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.quizzes.active</code>.
     */
    public Boolean getActive() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>public.quizzes.creation_date</code>.
     */
    public void setCreationDate(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.quizzes.creation_date</code>.
     */
    public Timestamp getCreationDate() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>public.quizzes.author_id</code>.
     */
    public void setAuthorId(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.quizzes.author_id</code>.
     */
    public Long getAuthorId() {
        return (Long) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, String, String, Integer, Boolean, Timestamp, Long> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Long, String, String, Integer, Boolean, Timestamp, Long> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Quizzes.QUIZZES.ID;
    }

    @Override
    public Field<String> field2() {
        return Quizzes.QUIZZES.TITLE;
    }

    @Override
    public Field<String> field3() {
        return Quizzes.QUIZZES.DESCRIPTION;
    }

    @Override
    public Field<Integer> field4() {
        return Quizzes.QUIZZES.TOTAL;
    }

    @Override
    public Field<Boolean> field5() {
        return Quizzes.QUIZZES.ACTIVE;
    }

    @Override
    public Field<Timestamp> field6() {
        return Quizzes.QUIZZES.CREATION_DATE;
    }

    @Override
    public Field<Long> field7() {
        return Quizzes.QUIZZES.AUTHOR_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getTitle();
    }

    @Override
    public String component3() {
        return getDescription();
    }

    @Override
    public Integer component4() {
        return getTotal();
    }

    @Override
    public Boolean component5() {
        return getActive();
    }

    @Override
    public Timestamp component6() {
        return getCreationDate();
    }

    @Override
    public Long component7() {
        return getAuthorId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getTitle();
    }

    @Override
    public String value3() {
        return getDescription();
    }

    @Override
    public Integer value4() {
        return getTotal();
    }

    @Override
    public Boolean value5() {
        return getActive();
    }

    @Override
    public Timestamp value6() {
        return getCreationDate();
    }

    @Override
    public Long value7() {
        return getAuthorId();
    }

    @Override
    public QuizzesRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public QuizzesRecord value2(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public QuizzesRecord value3(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public QuizzesRecord value4(Integer value) {
        setTotal(value);
        return this;
    }

    @Override
    public QuizzesRecord value5(Boolean value) {
        setActive(value);
        return this;
    }

    @Override
    public QuizzesRecord value6(Timestamp value) {
        setCreationDate(value);
        return this;
    }

    @Override
    public QuizzesRecord value7(Long value) {
        setAuthorId(value);
        return this;
    }

    @Override
    public QuizzesRecord values(Long value1, String value2, String value3, Integer value4, Boolean value5, Timestamp value6, Long value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached QuizzesRecord
     */
    public QuizzesRecord() {
        super(Quizzes.QUIZZES);
    }

    /**
     * Create a detached, initialised QuizzesRecord
     */
    public QuizzesRecord(Long id, String title, String description, Integer total, Boolean active, Timestamp creationDate, Long authorId) {
        super(Quizzes.QUIZZES);

        set(0, id);
        set(1, title);
        set(2, description);
        set(3, total);
        set(4, active);
        set(5, creationDate);
        set(6, authorId);
    }
}
