/*
 * This file is generated by jOOQ.
 */
package com.kopivad.quizzes.domain.db.tables.records;


import com.kopivad.quizzes.domain.db.tables.Quizzes;

import java.sql.Timestamp;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QuizzesRecord extends UpdatableRecordImpl<QuizzesRecord> implements Record8<Long, Boolean, Timestamp, String, String, Long, Integer, Long> {

    private static final long serialVersionUID = -1854482361;

    /**
     * Setter for <code>public.quizzes.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.quizzes.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.quizzes.active</code>.
     */
    public void setActive(Boolean value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.quizzes.active</code>.
     */
    public Boolean getActive() {
        return (Boolean) get(1);
    }

    /**
     * Setter for <code>public.quizzes.creation_date</code>.
     */
    public void setCreationDate(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.quizzes.creation_date</code>.
     */
    public Timestamp getCreationDate() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>public.quizzes.description</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.quizzes.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.quizzes.title</code>.
     */
    public void setTitle(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.quizzes.title</code>.
     */
    public String getTitle() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.quizzes.author_id</code>.
     */
    public void setAuthorId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.quizzes.author_id</code>.
     */
    public Long getAuthorId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.quizzes.total</code>.
     */
    public void setTotal(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.quizzes.total</code>.
     */
    public Integer getTotal() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.quizzes.group_id</code>.
     */
    public void setGroupId(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.quizzes.group_id</code>.
     */
    public Long getGroupId() {
        return (Long) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Long, Boolean, Timestamp, String, String, Long, Integer, Long> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Long, Boolean, Timestamp, String, String, Long, Integer, Long> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Quizzes.QUIZZES.ID;
    }

    @Override
    public Field<Boolean> field2() {
        return Quizzes.QUIZZES.ACTIVE;
    }

    @Override
    public Field<Timestamp> field3() {
        return Quizzes.QUIZZES.CREATION_DATE;
    }

    @Override
    public Field<String> field4() {
        return Quizzes.QUIZZES.DESCRIPTION;
    }

    @Override
    public Field<String> field5() {
        return Quizzes.QUIZZES.TITLE;
    }

    @Override
    public Field<Long> field6() {
        return Quizzes.QUIZZES.AUTHOR_ID;
    }

    @Override
    public Field<Integer> field7() {
        return Quizzes.QUIZZES.TOTAL;
    }

    @Override
    public Field<Long> field8() {
        return Quizzes.QUIZZES.GROUP_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Boolean component2() {
        return getActive();
    }

    @Override
    public Timestamp component3() {
        return getCreationDate();
    }

    @Override
    public String component4() {
        return getDescription();
    }

    @Override
    public String component5() {
        return getTitle();
    }

    @Override
    public Long component6() {
        return getAuthorId();
    }

    @Override
    public Integer component7() {
        return getTotal();
    }

    @Override
    public Long component8() {
        return getGroupId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Boolean value2() {
        return getActive();
    }

    @Override
    public Timestamp value3() {
        return getCreationDate();
    }

    @Override
    public String value4() {
        return getDescription();
    }

    @Override
    public String value5() {
        return getTitle();
    }

    @Override
    public Long value6() {
        return getAuthorId();
    }

    @Override
    public Integer value7() {
        return getTotal();
    }

    @Override
    public Long value8() {
        return getGroupId();
    }

    @Override
    public QuizzesRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public QuizzesRecord value2(Boolean value) {
        setActive(value);
        return this;
    }

    @Override
    public QuizzesRecord value3(Timestamp value) {
        setCreationDate(value);
        return this;
    }

    @Override
    public QuizzesRecord value4(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public QuizzesRecord value5(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public QuizzesRecord value6(Long value) {
        setAuthorId(value);
        return this;
    }

    @Override
    public QuizzesRecord value7(Integer value) {
        setTotal(value);
        return this;
    }

    @Override
    public QuizzesRecord value8(Long value) {
        setGroupId(value);
        return this;
    }

    @Override
    public QuizzesRecord values(Long value1, Boolean value2, Timestamp value3, String value4, String value5, Long value6, Integer value7, Long value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached QuizzesRecord
     */
    public QuizzesRecord() {
        super(Quizzes.QUIZZES);
    }

    /**
     * Create a detached, initialised QuizzesRecord
     */
    public QuizzesRecord(Long id, Boolean active, Timestamp creationDate, String description, String title, Long authorId, Integer total, Long groupId) {
        super(Quizzes.QUIZZES);

        set(0, id);
        set(1, active);
        set(2, creationDate);
        set(3, description);
        set(4, title);
        set(5, authorId);
        set(6, total);
        set(7, groupId);
    }
}
