/*
 * This file is generated by jOOQ.
 */
package com.kopivad.quizzes.domain.db.tables.records;


import com.kopivad.quizzes.domain.db.tables.UsrRoles;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsrRolesRecord extends UpdatableRecordImpl<UsrRolesRecord> implements Record3<Long, Long, String> {

    private static final long serialVersionUID = -427517030;

    /**
     * Setter for <code>public.usr_roles.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.usr_roles.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.usr_roles.user_id</code>.
     */
    public void setUserId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.usr_roles.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.usr_roles.role</code>.
     */
    public void setRole(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.usr_roles.role</code>.
     */
    public String getRole() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, Long, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Long, Long, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return UsrRoles.USR_ROLES.ID;
    }

    @Override
    public Field<Long> field2() {
        return UsrRoles.USR_ROLES.USER_ID;
    }

    @Override
    public Field<String> field3() {
        return UsrRoles.USR_ROLES.ROLE;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getUserId();
    }

    @Override
    public String component3() {
        return getRole();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getUserId();
    }

    @Override
    public String value3() {
        return getRole();
    }

    @Override
    public UsrRolesRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public UsrRolesRecord value2(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public UsrRolesRecord value3(String value) {
        setRole(value);
        return this;
    }

    @Override
    public UsrRolesRecord values(Long value1, Long value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsrRolesRecord
     */
    public UsrRolesRecord() {
        super(UsrRoles.USR_ROLES);
    }

    /**
     * Create a detached, initialised UsrRolesRecord
     */
    public UsrRolesRecord(Long id, Long userId, String role) {
        super(UsrRoles.USR_ROLES);

        set(0, id);
        set(1, userId);
        set(2, role);
    }
}
