/*
 * This file is generated by jOOQ.
 */
package com.kopivad.quizzes.domain.db.tables.records;


import com.kopivad.quizzes.domain.db.tables.UsrsGroups;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsrsGroupsRecord extends TableRecordImpl<UsrsGroupsRecord> implements Record2<Long, Long> {

    private static final long serialVersionUID = 280951422;

    /**
     * Setter for <code>public.usrs_groups.user_id</code>.
     */
    public void setUserId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.usrs_groups.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.usrs_groups.group_id</code>.
     */
    public void setGroupId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.usrs_groups.group_id</code>.
     */
    public Long getGroupId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Long, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return UsrsGroups.USRS_GROUPS.USER_ID;
    }

    @Override
    public Field<Long> field2() {
        return UsrsGroups.USRS_GROUPS.GROUP_ID;
    }

    @Override
    public Long component1() {
        return getUserId();
    }

    @Override
    public Long component2() {
        return getGroupId();
    }

    @Override
    public Long value1() {
        return getUserId();
    }

    @Override
    public Long value2() {
        return getGroupId();
    }

    @Override
    public UsrsGroupsRecord value1(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public UsrsGroupsRecord value2(Long value) {
        setGroupId(value);
        return this;
    }

    @Override
    public UsrsGroupsRecord values(Long value1, Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsrsGroupsRecord
     */
    public UsrsGroupsRecord() {
        super(UsrsGroups.USRS_GROUPS);
    }

    /**
     * Create a detached, initialised UsrsGroupsRecord
     */
    public UsrsGroupsRecord(Long userId, Long groupId) {
        super(UsrsGroups.USRS_GROUPS);

        set(0, userId);
        set(1, groupId);
    }
}
