/*
 * This file is generated by jOOQ.
 */
package com.kopivad.testingsystem.domain.db.tables;


import com.kopivad.testingsystem.domain.db.Indexes;
import com.kopivad.testingsystem.domain.db.Keys;
import com.kopivad.testingsystem.domain.db.Public;
import com.kopivad.testingsystem.domain.db.tables.records.UserResponcesRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserResponces extends TableImpl<UserResponcesRecord> {

    private static final long serialVersionUID = 585868450;

    /**
     * The reference instance of <code>public.user_responces</code>
     */
    public static final UserResponces USER_RESPONCES = new UserResponces();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserResponcesRecord> getRecordType() {
        return UserResponcesRecord.class;
    }

    /**
     * The column <code>public.user_responces.id</code>.
     */
    public final TableField<UserResponcesRecord, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('user_responces_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.user_responces.answer_id</code>.
     */
    public final TableField<UserResponcesRecord, Long> ANSWER_ID = createField(DSL.name("answer_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.user_responces.question_id</code>.
     */
    public final TableField<UserResponcesRecord, Long> QUESTION_ID = createField(DSL.name("question_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.user_responces.session_id</code>.
     */
    public final TableField<UserResponcesRecord, Long> SESSION_ID = createField(DSL.name("session_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>public.user_responces</code> table reference
     */
    public UserResponces() {
        this(DSL.name("user_responces"), null);
    }

    /**
     * Create an aliased <code>public.user_responces</code> table reference
     */
    public UserResponces(String alias) {
        this(DSL.name(alias), USER_RESPONCES);
    }

    /**
     * Create an aliased <code>public.user_responces</code> table reference
     */
    public UserResponces(Name alias) {
        this(alias, USER_RESPONCES);
    }

    private UserResponces(Name alias, Table<UserResponcesRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserResponces(Name alias, Table<UserResponcesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> UserResponces(Table<O> child, ForeignKey<O, UserResponcesRecord> key) {
        super(child, key, USER_RESPONCES);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.USER_RESPONCES_PKEY);
    }

    @Override
    public Identity<UserResponcesRecord, Long> getIdentity() {
        return Keys.IDENTITY_USER_RESPONCES;
    }

    @Override
    public UniqueKey<UserResponcesRecord> getPrimaryKey() {
        return Keys.USER_RESPONCES_PKEY;
    }

    @Override
    public List<UniqueKey<UserResponcesRecord>> getKeys() {
        return Arrays.<UniqueKey<UserResponcesRecord>>asList(Keys.USER_RESPONCES_PKEY);
    }

    @Override
    public List<ForeignKey<UserResponcesRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<UserResponcesRecord, ?>>asList(Keys.USER_RESPONCES__FKT4X7J4GV9GNVW9EQ16VQFQI46, Keys.USER_RESPONCES__FK323KVT7ONI5T0B0TR570YYN9T, Keys.USER_RESPONCES__FKKV6FTJCE5HFMCCH43JKBGG4OK);
    }

    public Answers answers() {
        return new Answers(this, Keys.USER_RESPONCES__FKT4X7J4GV9GNVW9EQ16VQFQI46);
    }

    public Questions questions() {
        return new Questions(this, Keys.USER_RESPONCES__FK323KVT7ONI5T0B0TR570YYN9T);
    }

    public QuizSessions quizSessions() {
        return new QuizSessions(this, Keys.USER_RESPONCES__FKKV6FTJCE5HFMCCH43JKBGG4OK);
    }

    @Override
    public UserResponces as(String alias) {
        return new UserResponces(DSL.name(alias), this);
    }

    @Override
    public UserResponces as(Name alias) {
        return new UserResponces(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserResponces rename(String name) {
        return new UserResponces(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserResponces rename(Name name) {
        return new UserResponces(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, Long, Long, Long> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
